### ISSUE TITLE
qc reduction due to excavation

### ISSUE THREAD

**Issue by daan108** [ritchie46/anaPile#3]
According to NEN9997-1 7.6.2.3(k) the measured cone resistance in sand and gravel should be reduced if an excavation takes place after the CPT was executed:
`q_c;z;ontgr = q_c;z * (s'_v;z;ontgr / s'_v;z;0) ^ t`
where 
q_c;z = qc from cpt
s'_v;z;ontgr = vertical effective stress in the soil at depth z after excavation
s'_v;z;0 = vertical effective stress in the soil at depth z at the time of cpt
t = power dependant on installation and order of work: 
- t=1 if installation is not low in vibration (niet-trillingsarm) **and** piles are installed after excavating
- t=0.5 if piles have been installed before excavation or installation is low-vibrating (trillingsarm).

(After this reduction cone resistances will be chamfered for Rs, not before)

**Comment by ritchie46** [comment]
You specifically say "sand and gravel". Does the qc value of other soil layers remain untouched?

**Comment by daan108** [comment]
That is correct. When the main component is Sand or Gravel will the measured cone resistance be reduced, the other soils remain untouched.

**Comment by daan108** [comment]
By the way, depth z before and after installation is the same level! I used the word depth but that is only when they refer to the same reference level.

**Comment by ritchie46** [comment]
closed in 953f3805c3edb0b5bbfc9a97492746426b0f8dec
